language: shell

jobs:
  include:
    - os: linux
      dist: focal
    - os: osx
      osx_image: xcode12.5

addons:
  apt:
    packages:
      - shellcheck
      - shunit2
  homebrew:
    packages:
      - shellcheck
      - shunit2

script:
  - make test
